### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by xQsme** [ryan-comer/discord-voice-commands-bot#1]
Hi,
Interesting idea, sadly I can't get it running, could you give me a little help?
Besides what is included in the readme, I also created google and IBM credentials in the location referenced in the Dockerfile.
My docker container logs seem incomplete, and seems to be just a huge object dump.
Are you able to run this current version?
Thanks

**Comment by ryan-comer** [comment]
If the logs look like an object dump, it's probably an error on an axios request. Go to the error status code and message and see what it says.  Post your logs here so I can help more.

You should download the Google API key file to the keys/ folder in the project root which can be downloaded from the Google console
You should also have an ibm-credentials.env in the keys/ folder which can be downloaded from the IBM Watson console

For the GOOGLE APIs, you have to enable the APIs on your cloud account (go to the APIs page). The one you'll need is the text to speech API

Make sure the .env has the required fields set.

The wake word that you need to say is 'Jarvis'. This can be seen in the /src/listener.js file

I'm going to be updating the README soon which might help.  There are some steps that I need to add.

**Comment by xQsme** [comment]
Ok my mistake was that I copied all the .env.example properties into my .env and spotify authentication was failing.
Thanks
